### ISSUE TITLE
Stixelnet working?

### ISSUE THREAD

**Issue by reedkotler** [erlikn/stixelnet#1]
Hi, I've been unable to get this to work. I get the following error:

$ python test_main.py
Traceback (most recent call last):
  File "test_main.py", line 41, in <module>
    import Data_IO.data_output as data_output
  File "/Users/reedkotler/Documents/wave/tensorflow-estimator/models/stixelnet/Data_IO/data_output.py", line 23, in <module>
    import Data_IO.kitti_shared as kitti
  File "/Users/reedkotler/Documents/wave/tensorflow-estimator/models/stixelnet/Data_IO/kitti_shared.py", line 20, in <module>
    import Data_IO.kitti_shared_ext_clsf_range as ext_clsf_range
ModuleNotFoundError: No module named 'Data_IO.kitti_shared_ext_clsf_range'
(tensorflow) Reeds-iMac:stixelnet reedkotler$ 

thanks.

**Comment by erlikn** [comment]
Oh, this is an old version of the project. We have moved the updated versions to a private repository as it is an ongoing research project. Once published the code will be released here. Thank you.

**Comment by dannyway03** [comment]
Hi, thanks for sharing! While I look forward to the next releases, would it be possible to get all the required source files to run this repo (it seems some are missing from the repo)? 
that would be indeed very nice :)
thanks!
